server:
  port: 8080
spring:
  application:
    name: challenge-full-stack-game
  data:
    mongodb:
      uri: "mongodb+srv://sofka:sofka@sofka.58bqo.mongodb.net/game?authSource=admin&compressors=zlib&retryWrites=true&w=majority&ssl=true"